### ISSUE TITLE
Missing communication around major changes.

### ISSUE THREAD

**Issue by jordam** [the-commons-project/vci-directory#26]
Hello!

Love the project.

Two days ago you added around 1,200 providers to the list.

Today you removed those providers.

What happened? 

As early advocates of this system and consumers of this resource as developers we would like a bit more information when major changes happen beyond 'added XYZ' 'removed XYZ' when referring to changing 99% of the content of the core file consumed in this repo.

It would help put our mind at ease and allow us to advocate for and develop with this system as it grows.

**Comment by jpp9** [comment]
thank you! yeah, absolutely, and also apologies for the flux. this directory will be an iterative process over the next couple of weeks as we onboard hundreds of (or more!) issuers. per your and other’s comments in issues, we have a bit of work to do in consistently labeling and defining the entities listed so that the directory is clear and workable for everyone. appreciate your patience as we work through it and we will communicate publicly in VCI outlets and on chat.fhir.org as we nail things down.

**Comment by laurencebgood** [comment]
Is there a mailing list that interested parties can subscribe to for updates on topics like this? I'm just a random dev and not part of an org that could join the VCI, but I'm interested in following along as I'll be working in my spare time on a validator project, possibly for future use by local businesses.
